### ISSUE TITLE
Extend the generation process for create a parent project with the needed module projects

### ISSUE THREAD

**Issue by astrapi69** [lightblueseas/gen-db-sources#1]
The generation process have to be extended for generate in first place a parent project. This parent project have then module projects. 
The module projects are in first place the entities, business, domain, init, rest-api, rest-client and rest-web.
The parent project have the 'data'-suffix in the project name. The structure of the project can be seen in the  reference project [resource-system-data](https://github.com/lightblueseas/resource-system-data)

**Comment by jimmyMaci** [comment]
This classes in init project are still not generated:
 	businessServicesTests

This files in init project are still not generated:
in test
 	test-applicationContext.xml
 	test-h2-applicationContext.xml
 	testng.xml
in main
 	persistence.xml
 	persistence-h2.xml
 	jdbc.properties
 	jdbc-h2.properties

**Comment by jimmyMaci** [comment]
This classes in rest-api project are still not generated:
RestfulResource-interfaces
RestfulResource-classes

This files in rest-api project are still not generated:
.gitignore

**Comment by jimmyMaci** [comment]
This classes in rest-client project are still not generated:
RestClient-class
RestClientTest-class

This files in rest-client project are still not generated:
.gitignore

**Comment by jimmyMaci** [comment]
This classes in rest-web project are still not generated:
in test
ApplicationJettyRunner

This files in rest-web project are still not generated:
.gitignore

in src/main/
			resources/
					META-INF/
							persistence.xml
							persistence-h2.xml
					application-context.xml
					data-application-context.xml
					data-h2-application-context.xml
					jdbc.properties
					jdbc-h2.properties
					project.properties
					web-application-context.xml
		
			/webapp/index.jsp
					META-INF/
							MANIFEST.MF
					WEB-INF/
							web.xml

**Comment by jimmyMaci** [comment]
All classes are generated now. I will close this issue
